spring:
  data:
    mongodb:
      database: chat_service
      port: 27018

  mongodb:
    embedded:
      version: 5.0.5

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 5.0.5

server:
  port: 8080
